### ISSUE TITLE
Continuous Integration

### ISSUE THREAD

**Issue by AaronGeesink** [raymondwzeng/cs180-housing-project#8]
Add Continuous Integration so that all unit tests are run automatically when the project is pushed to the repo.

**Comment by raymondwzeng** [comment]
There are two basic approaches to tackling this.
1. Refactor the code such that all tests on the server side happen independently of the API (that is, we will move any tests that call our server to the client side). We will only run server side unit tests on our CI framework.
2. Figure out how to handle CI with a server. It seems to involve setting up some sort of server on your own, then using SSH/something else to use that machine instead.
